MVC-AppUserProject/Models/Entities/Concrete/AppUser.cs
using MVC_AppUserProject.Models.Entities.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_AppUserProject.Models.Entities.Concrete
{
    public class AppUser:BaseEntity
    {
        public string  FirstName { get; set; }
        public string LastName { get; set; }
        
        public int UserRoleId { get; set; }
        public virtual UserRole UserRole { get; set; }

       
    }


}

MVC-AppUserProject/Controllers/AppUserController.cs
using MVC_AppUserProject.Models.DataTransferObjects;
using MVC_AppUserProject.Models.Entities.Abstract;
using MVC_AppUserProject.Models.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_AppUserProject.Controllers
{
    public class AppUserController:BaseController
    {
        #region Create


        [HttpGet]
        public ActionResult Create()
        {
            CreateAppUserDTO model = new CreateAppUserDTO();
            model.UserRole = db.UserRoles.Where(x => x.status != Status.Passive).ToList();
            return View(model);
        }


        [HttpPost]
        public ActionResult Create(CreateAppUserDTO model)
        {
            model.UserRole = db.UserRoles.Where(x => x.status != Status.Passive).ToList();
            if (ModelState.IsValid)
            {
                AppUser appUser = new AppUser();
                appUser.FirstName = model.FirstName;
                appUser.LastName = model.LastName;
                appUser.UserRoleId = model.UserRoleId;

               db.AppUsers.Add(appUser);
               db.SaveChanges();
               ViewBag.alert = 1;
               return View(model);
            }

            else

            {
                ViewBag.alert = 2;
                return View(model);
            }

        }
        #endregion




        #region list

        public ActionResult List()
        {
            ///[version-1]
            //var appUserList = db.AppUsers.Where(x => x.status != Status.Passive).ToList();
            //return View(appUserList);


           /// [verion-2 SP]
            return View(db.AppUsers.SqlQuery("execute GetProcess").ToList());
        }
        #endregion



        #region Detail
        public ActionResult Details(int id)
        {
            return View(db.AppUsers.SqlQuery("execute GetProcess").FirstOrDefault(x => x.Id == id));
        }
        #endregion



        #region Update

        [HttpGet]
        public ActionResult Update(int id)
        {
            AppUser appUser = db.AppUsers.SqlQuery("execute GetProcess").FirstOrDefault(x=>x.Id==id);
            UpdateAppUserDTO model = new UpdateAppUserDTO();
            model.FirstName = appUser.FirstName;
            model.LastName = appUser.LastName;
            model.UserRole=db.UserRoles.Where(x => x.status != Status.Passive).ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(UpdateAppUserDTO model)
        {
            AppUser appUser = db.AppUsers.FirstOrDefault(x => x.Id == model.Id);
            if (ModelState.IsValid)
            {
               // var param= new  SqlParameter("@id, @firstName,  @lastname, @UserRoleId", model.Id, model.FirstName, model.LastName, model.UserRoleId);
               // db.Database.SqlQuery<AppUser>("execute UpdateProcess  @firstName,  @lastname, @UserRoleId", param).ToList();
                appUser.FirstName = model.FirstName;                    
                appUser.LastName = model.LastName;                       
                appUser.UserRoleId = model.UserRoleId;
                appUser.UpdateDate = DateTime.Now;
                appUser.status = Status.Modified;                
                db.SaveChanges();
                ViewBag.alert = 1;
                return RedirectToAction("List");
            }
            else 
            {
                ViewBag.alert = 2;
                return View(model);
            }

        }
        #endregion


        #region Delete
        public ActionResult Delete(int id)
        {
            // AppUser appUser = db.AppUsers.FirstOrDefault(x => x.Id == id);
            //appUser.status = Status.Passive;
            //appUser.DeleteDate = DateTime.Now;     
            // ViewBag.alert = 1;
            //  return RedirectToAction("List");
           db.Database.SqlQuery<AppUser>("execute DeleteProcess @id", new SqlParameter("@id", id)).FirstOrDefault(x => x.Id == id);
            return RedirectToAction("List");
        }
        
        #endregion
    }
}

MVC-AppUserProject/Views/AppUser/Create.cshtml
@model MVC_AppUserProject.Models.DataTransferObjects.CreateAppUserDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

    <div class="container" style="margin-top: 20px">

        <div class="row">
            <div class="col-sm-6">
                
                @Html.Partial("/Views/Shared/Partial/_AlertMessage.cshtml")
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Create AppUser</h3>
                    </div>
                    <form role="form" method="post" action="/AppUser/Create">
                        <div class="box-body">
                            <div class="form-group">

                                @Html.LabelFor(x => x.FirstName)
                                @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control from-success", @placeholder = "Firstname" })
                                @Html.ValidationMessageFor(x => x.FirstName)

                            </div>
                            <div class="form-group">

                                @Html.LabelFor(x => x.LastName)
                                @Html.TextBoxFor(x => x.LastName, new { @class = "form-control", @placeholder = "lastname" })
                                @Html.ValidationMessageFor(x => x.LastName)
                            </div>

                            <div class="form-group">

                                <label for="UserRoleId">Choose a Role</label>
                                <select name="UserRoleId" class="form-control">
                                    @foreach (var UserRole in Model.UserRole)
                                    {
                                        <option value="@UserRole.Id">@UserRole.RoleName</option>
                                    }
                                </select>
                                <span class="field-validation-valid" data-valmsg-for="UserRoleId" data-valmsg-replace="true"></span>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success" style="float:right">Submit</button>
                            </div>
                        </div>

                        <div class="box-footer">
                            @Html.ActionLink("Show to List", "List", "AppUser", new { @class = "btn btn-warning btn-block", @type = "button" })
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

MVC-AppUserProject/Views/AppUser/Details.cshtml
@model MVC_AppUserProject.Models.Entities.Concrete.AppUser
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>AppUser Informations</h2>

<h2>Details </h2>

<h4>Id: @Model.Id</h4>
<h4>First Name: @Model.FirstName</h4>
<h4>LastName: @Model.LastName</h4>
<h4>Role: @Model.UserRole.RoleName</h4>
<h4>Status: @Model.status</h4>
<h4>Update Date : @Model.UpdateDate</h4>
<h4>Create Date: @Model.CreateDate</h4>

MVC-AppUserProject/Views/AppUser/List.cshtml
@model List<MVC_AppUserProject.Models.Entities.Concrete.AppUser>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="container" style="margin-top:20px">
    <center>
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">AppUser List</h4>
                    </div>
                    <div class="box-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>FirstName</th>
                                    <th>LastName</th>
                                    <th>User Role</th>

                                    <th>Update</th>
                                    <th>Detail</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var appUser in Model)
                                {
                                    <tr>
                                        <td>@appUser.Id</td>
                                        <td>@appUser.FirstName</td>
                                        <td>@appUser.LastName</td>
                                        <td>@appUser.UserRole.RoleName</td>

                                        <td>
                                            <a href="/AppUser/Update/@appUser.Id" class="btn btn-success btn-sm">Update</a>
                                        </td>
                                        <td>
                                            <a href="/AppUser/Details/@appUser.Id" class="btn btn-primary btn-sm">Details</a>
                                        </td>
                                        <td>
                                            <a href="/AppUser/Delete/@appUser.Id" class="btn btn-warning btn-sm">Delete</a>
                                            
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="box-footer">
                        <a href="/AppUser/Create" class="btn btn-primary btn-block">Create New AppUser</a>
                    </div>
                </div>
            </div>
        </div>
    </center>
</div>

MVC-AppUserProject/Views/AppUser/Update.cshtml
@model MVC_AppUserProject.Models.DataTransferObjects.UpdateAppUserDTO
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="container" style="margin-top: 20px">

    <div class="row">
        <div class="col-sm-6">
            @Html.Partial("/Views/Shared/Partial/_AlertMessage.cshtml")

          @*  <a href="/Views/Shared/Partial/_AlertMessage.cshtml"></a>*@
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Update AppUser</h3>
                </div>
                <form role="form" method="post" action="/AppUser/Update">
                    @Html.HiddenFor(x => x.Id);
                    
                    <div class="box-body">
                        <div class="form-group">

                            @Html.LabelFor(x => x.FirstName)
                            @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control from-success", @placeholder = "Firstname" })
                            @Html.ValidationMessageFor(x => x.FirstName)

                        </div>

                        <div class="form-group">

                            @Html.LabelFor(x => x.LastName)
                            @Html.TextBoxFor(x => x.LastName, new { @class = "form-control", @placeholder = "Last name" })
                            @Html.ValidationMessageFor(x => x.LastName)
                        </div>

                        <div class="form-group">

                            <label for="UserRoleId">Choose a Role</label>
                            <select name="UserRoleId" class="form-control">
                                @foreach (var UserRole in Model.UserRole)
                                {
                                    <option value="@UserRole.Id">@UserRole.RoleName</option>
                                }
                            </select>
                            <span class="field-validation-valid" data-valmsg-for="UserRoleId" data-valmsg-replace="true"></span>
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-success" style="float:right">Submit</button>
                        </div>
                    </div>
                    <div class="box-footer">
                        @Html.ActionLink("Show to List", "List", "AppUser", new { @class = "btn btn-warning btn-block", @type = "button" })
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>