MVC-AppUserProject/Models/Entities/Concrete/UserRole.cs
using MVC_AppUserProject.Models.Entities.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_AppUserProject.Models.Entities.Concrete
{
    public class UserRole:BaseEntity
    {
        public string RoleName { get; set; }
        public decimal Salery { get; set; }
        public string  Description { get; set; }
        public virtual List<AppUser> AppUsers{ get; set; }
}
}

MVC-AppUserProject/Controllers/UserRoleController.cs
using MVC_AppUserProject.Models.DataTransferObjects;
using MVC_AppUserProject.Models.Entities.Abstract;
using MVC_AppUserProject.Models.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_AppUserProject.Controllers
{
    public class UserRoleController : BaseController
    {
        #region CREATE

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Create(CreateUserRoleDTO model)
        {
            model.UserRoles = db.UserRoles.Where(x => x.status != Status.Passive).ToList();
            if(ModelState.IsValid)
            {
                UserRole userRole = new UserRole();
                userRole.RoleName = model.RoleName;
                userRole.Salery = model.Salery;
                userRole.Description = model.Description;
                userRole.CreateDate = DateTime.Now;
                db.UserRoles.Add(userRole);
                db.SaveChanges();
                ViewBag.alert = 1;
                return Json(userRole);

            }
            else
            {
                return Json(model);
            }
        }
        #endregion



        #region LİST
        public ActionResult List()
        {
            var RoleList = db.UserRoles.Where(x => x.status != Status.Passive).ToList();
            return View(RoleList);
        }
        #endregion


        #region DELETE
        public JsonResult Delete(int id)
        {
            UserRole userrole = db.UserRoles.FirstOrDefault(x=>x.Id==id);
            userrole.status = Status.Passive;
            userrole.DeleteDate = DateTime.Now;
            db.SaveChanges();
            ViewBag.alert = 1;
            return Json("");

        }

        #endregion

        #region DETAİL
        public ActionResult Details(int id)
        {
            return View(db.UserRoles.FirstOrDefault(x => x.Id == id));
        }

        #endregion

        #region UPDATE
        public ActionResult Update(int id)
        {
            UserRole UserRole = db.UserRoles.FirstOrDefault(x => x.Id == id);
            UpdateUserRoleDTO model = new UpdateUserRoleDTO();
            model.RoleName = UserRole.RoleName;
            model.Description = UserRole.Description;
            model.Salery = UserRole.Salery;
            model.UserRole = db.UserRoles.Where(x =>x.status != Status.Passive).ToList();

            return View(model);
        }

        [HttpPost]
        public JsonResult Update(UpdateUserRoleDTO model)
        {
            UserRole UserRole = db.UserRoles.FirstOrDefault(x => x.Id == model.Id);
            if (ModelState.IsValid)
            {
                UserRole.RoleName = model.RoleName;
                UserRole.Description = model.Description;
                UserRole.Salery = model.Salery;
                UserRole.UpdateDate = DateTime.Now;
                UserRole.status = Status.Modified;
                db.SaveChanges();
                ViewBag.alert = 1;
                return Json(UserRole);
            }
            else
            {
                ViewBag.alert = 2;
                return Json(model);
            }
        }
            #endregion
        }
}

MVC-AppUserProject/Views/UserRole/Create.cshtml
@model MVC_AppUserProject.Models.DataTransferObjects.CreateUserRoleDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="container" style="margin-top:20px">
    <div class="row">
        <div class="col-sm-6">
            @Html.Partial("/Views/Shared/Partial/_AlertMessage.cshtml")

            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Create UserRole</h3>
                </div>
                <form action="/UserRole/Create" method="post">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="RoleName">Role Name</label>
                            <input class="form-control" name="RoleName" placeholder="User Role Name" type="text" />
                            <span class="field-validation-valid" data-valmsg-for="RoleName" data-valmsg-replace="true"></span>
                        </div>

                        <div class="form-group">
                            <label for="Description">Description</label>
                            <input class="form-control" name="Description" placeholder="Description" type="text">
                            <span class="field-validation-valid" data-valmsg-for="Description" data-valmsg-replace="true"></span>
                        </div>
                        <div class="form-group">
                            <label for="Salery">Salery</label>
                            <input class="form-control" name="Salery" placeholder="Salery" type="text">
                            <span class="field-validation-valid" data-valmsg-for="Salery" data-valmsg-replace="true"></span>
                        </div>                                             
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary" style="float:right">Submit</button>
                        </div>
                    </div>


                    <div class="box-footer">
                        <a class="btn btn-warning btn-block" href="/UserRole/List?Length=8">Back to RoleList</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(".btn btn-primary").click(function ()
    {
        $.ajax({
            url: @Url.Action("Create","UserRole"),
            type: "POST",
            dataType: "json",
            data: {"model":model}
            
            success: function (data)
            {
                $("#a_" + model).add();
            }
        })
    })

</script>

MVC-AppUserProject/Views/UserRole/Details.cshtml
@model MVC_AppUserProject.Models.Entities.Concrete.UserRole
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>UserRole Detail</h2>


<h4>Id: @Model.Id</h4>
<h4>Role Name: @Model.RoleName</h4>
<h4>Description:@Model.Description</h4>
<h4>Salery: @Model.Salery</h4>
<h4>Status: @Model.status</h4>
<h4>Update Date : @Model.UpdateDate</h4>
<h4>Create Date: @Model.CreateDate</h4>

MVC-AppUserProject/Views/UserRole/List.cshtml
@model List<MVC_AppUserProject.Models.Entities.Concrete.UserRole>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="container" style="margin-top:20px">
    <center>
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-header">
                        <h4 class="box-title">UserRole List</h4>
                    </div>
                    <div class="box-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>RoleName</th>
                                    <th>Description</th>
                                    <th>Salery</th>

                                    <th>Update</th>
                                    <th>Detail</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var userRole in Model)
                                {
                                   
                                    <tr id="a_@userRole.Id">

                                        <td>@userRole.Id</td>
                                        <td>@userRole.RoleName</td>
                                        <td>@userRole.Description</td>
                                        <td>@userRole.Salery</td>


                                        <td>
                                            <a href="/UserRole/Update/@userRole.Id" class="btn btn-success btn-sm">Update</a>
                                        </td>
                                        <td>
                                            <a href="/UserRole/Details/@userRole.Id" class="btn btn-primary btn-sm">Details</a>
                                        </td>
                                        <td>
                                            @*<a href="/UserRole/Delete/@userRole.Id" class="btn btn-warning btn-sm">Delete</a>*@
                                            <input type="button" onclick="Delete('@userRole.Id')" value="Delete" name="Delete" class="btn btn-warning btn-sm" />
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                        </table>
                    </div>
                    <div class="box-footer">
                        <a href="/UserRole/Create" class="btn btn-primary btn-block">Create New UserRole</a>
                    </div>
                </div>
            </div>
        </div>
    </center>
</div>
<script type="text/javascript">
    $(".btn btn-primary").click(function () {
        $.ajax({
            url: "/UserRole/Update/" + model,
            type: "POST",
            dataType: "json",
            data:
            {
                "model": model
            },
            success: function () { $("#a_" + model).add(); }
        })
    })

</script>

<script>
    function Delete(id)
    {
        
        $.ajax({
            url: "/UserRole/Delete/" + id,
            type: "POST",
            success: function () { $("#a_"+id).fadeOut(); }
        });
    }
</script>

MVC-AppUserProject/Views/UserRole/Update.cshtml
@model MVC_AppUserProject.Models.DataTransferObjects.UpdateUserRoleDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="container" style="margin-top:20px">
    <div class="row">
        <div class="col-sm-6">
            @Html.Partial("/Views/Shared/Partial/_AlertMessage.cshtml")
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Update UserRole</h3>
                </div>
                <form action="/UserRole/Update" method="post">
                   
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <div class="box-body">
                        <div class="form-group">
                            <label for="RoleName">Role Name</label>
                            <input class="form-control" name="RoleName" placeholder="User Role Name" type="text" />
                            <span class="field-validation-valid" data-valmsg-for="RoleName" data-valmsg-replace="true"></span>
                        </div>
                        <div class="form-group">
                            <label for="Description">Description</label>
                            <input class="form-control" name="Description" placeholder="Description" type="text">
                            <span class="field-validation-valid" data-valmsg-for="Description" data-valmsg-replace="true"></span>
                        </div>
                        <div class="form-group">
                            <label for="Salery">Salery</label>
                            <input class="form-control" name="Salery" placeholder="Salery" type="text">
                            <span class="field-validation-valid" data-valmsg-for="Salery" data-valmsg-replace="true"></span>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary" style="float:right">Submit</button>
                        </div>
                    </div>


                    <div class="box-footer">
                        <a class="btn btn-warning btn-block" href="/UserRole/List?Length=8">Back to RoleList</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>